# Global settings for the image
[image]
width = 1200 # Recommended canvas width for OG Image
height = 630 # Recommended height width for OG Image
padding = 20 # Commmon padding for entire canvas

[[fonts]]
name = "JetBrainsMono"
path = "fonts/jetbrains-mono.ttf"

# Background settings
[background]
fill = "#121212"

[[background.borders]]
stroke = "#3F5878"
stroke_width = 20
side = "Bottom"

# Title configuration
[[sections]]
preamble_key = "title"  # Path to the title in the preamble, top-level key
wrap_lines = true       # Whether to line-wrap the text
font_size = 60          # Font size for title text
font_weight = "Bold"    # Font weight for title
fill = "#f2f8f8"        # Text color for title

# Date configuration
[[sections]]
preamble_key = "date"      # Path to the date in the preamble
font_size = 40             # Font size for date text
fill = "#f2f8f8"           # Text color for date
date_format = "%d.%m.%Y"   # Date format for parsing/formatting

# Tags configuration under the "taxonomies" section
[[sections]]
preamble_key = "taxonomies.tags"  # Nested path in preamble
optional = true
font_size = 25                    # Font size for tag text
fill = "#121212"                  # Text color for tag label
background = { fill = "#f2f8f8", padding = 5 }
list = { margin = 10 }