[image]
# Width of the output image in pixels.
width = 1200

# Height of the output image in pixels.
height = 630

# Padding around the content in the image, in pixels.
padding = 20

[[fonts]]
# Name of the font, used for referencing in the configuration.
name = "JetBrains Mono"

# Path to the font file, relative to the git root.
path = "fonts/jetbrains-mono.ttf"

[[fonts]]
name = "JetBrains Mono"
path = "fonts/jetbrains-mono-bold.ttf"

[[fonts]]
name = "Rubik"
path = "fonts/rubik.ttf"

[[fonts]]
name = "Rubik"
path = "fonts/rubik-bold.ttf"

[background]
# Background fill color for the entire image, specified in hex code.
fill = "#222436"

[[background.borders]]
# Border color for the image, specified in hex code.
stroke = "#444a73"

# Width of the border, in pixels.
stroke_width = 20

# The side of the image where the border will be drawn. Possible values are "Left", "Right", "Top", or "Bottom".
side = "Bottom"

[[sections]]
# Key from the preamble to use for this section, which identifies the content to display (e.g., title).
preamble_key = "title"

# Whether the text should wrap to a new line if it exceeds the image width. If false, the text will be truncated or continue off the image.
wrap_lines = true

# The font family to use for the text in this section, corresponding to the `name` specified in the `fonts` list.
font_family = "Rubik"

# Font size for the text in this section, in pixels.
font_size = 60

# Font weight for the text. Possible values are "Regular" or "Bold".
font_weight = "Bold"

# Text fill color for this section, specified in hex code.
fill = "#c8d3f5"

[[sections]]
# Format to use for combining multiple keys into a single line. Curly braces `{}` indicate placeholders.
format = "{date} :: {author}"

# Default values to use if any of the keys in the format are missing from the preamble.
default_values = { author = "dadyarri" }

# Font family to use for the formatted text.
font_family = "JetBrains Mono"

# Font size for the formatted text, in pixels.
font_size = 40

# Fill color for the formatted text, specified in hex code.
fill = "#c8d3f5"

# Date format to use when rendering date values in this section. Follows `chrono` formatting conventions.
date_format = "%d.%m.%Y"

[[sections]]
# Key from the preamble to use for this section. This section is optional, meaning it's okay if the key is missing.
preamble_key = "taxonomies.tags"

# Indicates if this section is optional. If true, missing data won't cause an error. False by default
optional = true

# Font family to use for this section.
font_family = "JetBrains Mono"

# Font size for the text in this section, in pixels.
font_size = 25

# Text fill color for this section, specified in hex code.
fill = "#222436"

# Optional background configuration for this section.
background = { fill = "#c8d3f5", padding = 10 }

# List configuration for rendering items in this section.
list = { margin = 10 }
