name = "yarri"
description = "Modern and minimalistic blog theme based on kanagawa"
min_version = "0.14.0"
license = "MIT"
homepage = "https://github.com/dadyarri/portfolio"
demo = "https://dadyarri.ru"

[author]
name = "dadyarri"
homepage = "https://github.com/dadyarri"
