name: Create Pull Request on new post

on:
  push:
    branches:
      - 'posts/*'
      - 'minis/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get the branch name without 'posts/' prefix
        id: branch_name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}  # Extract branch name (without refs/heads/)
          if [[ "$BRANCH_NAME" == posts/* ]]; then
            CONTENT_TYPE="post"
          elif [[ "$BRANCH_NAME" == minis/* ]]; then
            CONTENT_TYPE="mini"
          else
            echo "Branch does not match expected prefixes."
            exit 1
          fi
          CONTENT_NAME=${BRANCH_NAME#*/}
          echo "content_type=$CONTENT_TYPE" >> $GITHUB_OUTPUT
          echo "content_name=$CONTENT_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Draft of ${{ steps.branch_name.outputs.content_type }} \"${{ steps.branch_name.outputs.content_name }}\""
          draft: always-true
          branch: ${{ github.ref_name }}  # The current branch (e.g., 'posts/some-post')
          base: main
          body: "This pull request contains the draft for the ${{ steps.branch_name.outputs.content_type }} from branch `${{ steps.branch_name.outputs.content_name }}`."
          assignees: dadyarri
