name: Create Pull Request on posts/*|minis/* branch push

on:
  push:
    branches:
      - 'posts/*'
      - 'minis/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get the branch name without 'posts/' prefix
        id: branch_name
        run: |
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "post_name=${{ steps.branch_name.outputs.branch#posts/ }}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Draft of post \"${{ steps.branch_name.outputs.post_name }}\""
          branch: ${{ github.ref_name }}  # The current branch (e.g., 'posts/some-post')
          base: main
          body: "This pull request contains the draft for the post from branch `posts/${{ steps.branch_name.outputs.post_name }}`."
