name: Generate OG images on PR merge

on:
  push:
    branches:
      - 'main'

jobs:
  update-og-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'

      - name: Build OgImages
        run: |
          dotnet publish OgImages/OgImages/OgImages.csproj -r linux-x64 -c Release

      - name: Generate OG image for merged content
        run: |
          chmod +x ./OgImages/OgImages/bin/Release/net9.0/linux-x64/OgImages
          ./OgImages/OgImages/bin/Release/net9.0/linux-x64/OgImages --all

      - name: Commit and push new OG images
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "updated og-images"
            git push
          else
            echo "No changes to commit"
          fi
