name: Generate OG images on PR merge

on:
  push:
    branches:
      - 'main'

jobs:
  update-og-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate OG image for merged content
        run: |
          ./bin/OgImages --all

      - name: Commit and push new OG images
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "updated og-images"
            git push
          else
            echo "No changes to commit"
          fi
